from dash import html, dcc


def metrics_panel():
    return html.Div(
        style={
            "width": "360px",
            "padding": "22px 18px",
            "borderRight": "2px solid #1f1f1f",
            "overflowY": "auto",
            "background": "#ffffff",
        },
        children=[
            html.H1(
                "Global Metrics",
                style={"margin": "0 0 18px 0", "fontSize": "44px", "fontWeight": "500"},
            ),
            html.H2("Economic", style={"fontSize": "34px", "margin": "14px 0 10px 0", "fontWeight": "500"}),
            dcc.Checklist(
                id="metric-checklist",
                options=[
                    {"label": "Unemployment rate", "value": "unemployment"},
                    {"label": "GDP per capita", "value": "gdp_pc"},
                ],
                value=["unemployment", "gdp_pc"],
                inputStyle={"marginRight": "10px"},
                labelStyle={"display": "block", "marginBottom": "8px", "fontSize": "16px"},
            ),
            html.Div("Importance", style={"marginTop": "8px", "fontSize": "16px"}),
            dcc.Slider(
                id="w-unemployment",
                min=0,
                max=100,
                step=1,
                value=60,
                marks={0: "0", 100: "100"},
                tooltip={"placement": "bottom", "always_visible": True},
            ),
            html.Div(style={"height": "14px"}),
            dcc.Slider(
                id="w-gdp_pc",
                min=0,
                max=100,
                step=1,
                value=70,
                marks={0: "0", 100: "100"},
                tooltip={"placement": "bottom", "always_visible": True},
            ),
            html.Hr(style={"margin": "22px 0", "opacity": 0.3}),
            html.H2("Demographic", style={"fontSize": "34px", "margin": "14px 0 10px 0", "fontWeight": "500"}),
            dcc.Checklist(
                id="metric-checklist-dem",
                options=[
                    {"label": "Youth unemployment rate", "value": "youth_unemp"},
                    {"label": "Population growth rate", "value": "pop_growth"},
                ],
                value=["youth_unemp", "pop_growth"],
                inputStyle={"marginRight": "10px"},
                labelStyle={"display": "block", "marginBottom": "8px", "fontSize": "16px"},
            ),
            html.Div("Importance", style={"marginTop": "8px", "fontSize": "16px"}),
            dcc.Slider(
                id="w-youth_unemp",
                min=0,
                max=100,
                step=1,
                value=50,
                marks={0: "0", 100: "100"},
                tooltip={"placement": "bottom", "always_visible": True},
            ),
            html.Div(style={"height": "14px"}),
            dcc.Slider(
                id="w-pop_growth",
                min=0,
                max=100,
                step=1,
                value=40,
                marks={0: "0", 100: "100"},
                tooltip={"placement": "bottom", "always_visible": True},
            ),
            html.Hr(style={"margin": "22px 0", "opacity": 0.3}),
            html.H2(
                "Sustainability",
                style={"fontSize": "34px", "margin": "14px 0 10px 0", "fontWeight": "500"},
            ),
            dcc.Checklist(
                id="metric-checklist-sus",
                options=[
                    {"label": "Electricity access %", "value": "elec_access"},
                    {"label": "Electricity generating capacity (relative)", "value": "elec_capacity"},
                ],
                value=["elec_access", "elec_capacity"],
                inputStyle={"marginRight": "10px"},
                labelStyle={"display": "block", "marginBottom": "8px", "fontSize": "16px"},
            ),
            html.Div("Importance", style={"marginTop": "8px", "fontSize": "16px"}),
            dcc.Slider(
                id="w-elec_access",
                min=0,
                max=100,
                step=1,
                value=65,
                marks={0: "0", 100: "100"},
                tooltip={"placement": "bottom", "always_visible": True},
            ),
            html.Div(style={"height": "14px"}),
            dcc.Slider(
                id="w-elec_capacity",
                min=0,
                max=100,
                step=1,
                value=55,
                marks={0: "0", 100: "100"},
                tooltip={"placement": "bottom", "always_visible": True},
            ),
        ],
    )
